version: '3'

services:
  warehouse:
    build: .
    environment:
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwh
      POSTGRES_DB: dwh
    volumes:
      - postgres-dwh-volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "5455:5432"

volumes:
  postgres-dwh-volume: