name: schedule_dbt

on: [push]

jobs:
  schedule_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'