name: schedule_dbt

on: [push]

env:
  DBT_PROFILES_DIR: ./

jobs:
  schedule_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dbt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.4.6
      - name: Test dbt
        run: dbt test